local a = {
["200000000"] = {
   id = "200000000",
   point_lv = "1",
   point_demand = "5000",
   item_id = "1",
   item_num = "1000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000001"] = {
   id = "200000001",
   point_lv = "2",
   point_demand = "30000",
   item_id = "1",
   item_num = "6000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000002"] = {
   id = "200000002",
   point_lv = "3",
   point_demand = "70000",
   item_id = "1",
   item_num = "12000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000003"] = {
   id = "200000003",
   point_lv = "4",
   point_demand = "150000",
   item_id = "1",
   item_num = "30000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000004"] = {
   id = "200000004",
   point_lv = "5",
   point_demand = "400000",
   item_id = "1",
   item_num = "75000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000005"] = {
   id = "200000005",
   point_lv = "6",
   point_demand = "800000",
   item_id = "1",
   item_num = "180000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000006"] = {
   id = "200000006",
   point_lv = "7",
   point_demand = "1600000",
   item_id = "1",
   item_num = "360000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000007"] = {
   id = "200000007",
   point_lv = "8",
   point_demand = "4000000",
   item_id = "1",
   item_num = "1000000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["200000008"] = {
   id = "200000008",
   point_lv = "9",
   point_demand = "8000000",
   item_id = "1",
   item_num = "2000000",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
["nil"] = {
   id = "",
   point_lv = "",
   point_demand = "",
   item_id = "",
   item_num = "",
   NULL = "",
   NULL = "",
   NULL = "",
   },
}
return a
